<html><head>
<style>

ul {
    list-style-type: none;
    margin: 10;
    padding: 0;
    overflow: hidden;
    background-color: black;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: grey;
}


</style>
</head><body><ul>
  <li><a class="active" href="http://localhost/first.php">Home</a></li>
  <li><a href="http://localhost/contact.php">Contact Us</a></li>
  <li><a href="http://localhost/about.php">About</a></li>
</ul>
<BR>
<H1>PERSONA</H1>
<H2 ALIGN="CENTER">"Your Personality Matters!" Come, express yourself and your talent in this exciting competition in which people from various colleges will compete for the title of Mr. and Ms. SPANDAN. </H2>
<br>
<a target="_blank" href="http://localhost/formn.php">To Register Click Here</a>
   
<H2 ALIGN="CENTER"> CONTACT:</H2>
<BR>
<H2 ALIGN="CENTER">sHRUTI: +917756378907</H2>
</body></html>