<html><head>
<link rel="stylesheet" href="navigation.css">
<link rel="stylesheet" href="regbutton.css">

</head>
<body>

<div class="header" align="left">
<div class="left"><img src="logo1.jpg" width="130px"></div>
<div calss="right">
<h2 style="font-size:30px;font-family:Arial,sans-serif;"><font color="white"><br><br>Spandan2018</font></h2>
</div>
<div class="bot">
<ul>
  <li><a href="first.php">Home</a></li>

  <li><a href="contact us.php">Contact</a></li>
  <li style="float:right"><a href="#about">About</a></li>
</ul>
</div>
</div>

<BR>
<H1 align="center"><font color="TEAL">PERSONA</font></H1>
<H2 ALIGN="CENTER" class="para">"Personalty is an unbroken series of successful gestures"<br><h5 ALIGN="CENTER" class="para">-F. Scott Fitzgerald</h5></h2>



<p>
"Your Personality Matters!" Come, express yourself and your talent in this exciting competition in which people from various colleges will compete for the title of Mr. and Ms. SPANDAN. Prove them that you have that charismatic personality that deserves most attention and appreciation.IMPRESS THEM ALL
<br><br> <h3 class="para">DAY 1 : 4th February 2018</h3> 

</p>
<br>
<br>

<center>
<a class="sub" href="formn.php" target="_blank">Register here</a>
</center>

<H4 ALIGN="CENTER"> CONTACT:</H2>

<H4 ALIGN="CENTER">SHRUTI: +917756378907</H2>
</body></html>