<html><head><link rel="stylesheet" href="navigation.css">
<link rel="stylesheet" href="regbutton.css"></head>


<body>

<div class="header" align="left">
<div class="left"><img src="logo1.jpg" width="130px"></div>
<div calss="right">
<h2 style="font-size:30px;font-family:Arial,sans-serif;"><font color="white"><br><br>Spandan2018</font></h2>
</div>
<div class="bot">
<ul>
  <li><a href="first.php">Home</a></li>

  <li><a href="contact us.php">Contact</a></li>
  <li style="float:right"><a href="#about">About</a></li>
</ul>
</div>
</div>

<BR>
<H1 align="center"><font color="TEAL">XIE DANCE +</font></H1>
<H2 ALIGN="CENTER" class="para">To Dance is an expression of one's individuality! </h2>
<p>So turn your dance modes On and come in groups to express yourself and show the world how well can you coordinate.Compete with some of the best groups in Mumbai and leave everyone amazed with your dance moves.Feel the heat. STEP UP
<br><br> <h3 class="para">DAY 1 : 4th February 2018</h3>  </p>

<br>





   
<h2 class="para" align="center">Spandan 2018 presents Clique Ecstasy, The Group Dance event of XIE!  </H2>

<center>
<a class="sub" href="dnce+.php" target="_blank">Register here</a>
</center>

<H4 ALIGN="CENTER"> CONTACT:</H2>

<H4 ALIGN="CENTER">CHAITRALI: +917756378907</H2>
</body></html>