<html><link rel="stylesheet" href="navigation.css">
<link rel="stylesheet" href="regbutton.css"></head>

<body >

<div class="header" align="left">
<div class="left"><img src="logo1.jpg" width="130px"></div>
<div calss="right">
<h2 style="font-size:30px;font-family:Arial,sans-serif;"><font color="white"><br><br>Spandan2018</font></h2>
</div>
<div class="bot">
<ul>
  <li><a href="first.php">Home</a></li>

  <li><a href="contact us.php">Contact</a></li>
  <li style="float:right"><a href="#about">About</a></li>
</ul>
</div>
</div>

<BR>

<H1 align="center"><font color="TEAL">CHAI TIME WITH KENNY</font></H1>

<H2 ALIGN="CENTER" class="para">Give it up for the singer, actor, mimicry artist, standup comedian all in one Mr. KENNY SEBASTIAN!</H2><BR>

<p>Enjoy a packed night of uncontrollable laughs and unlimited fun.Join Kenny Sebastian on a intimate sit down comedy show, Where he sips on a cup of tea as he delivers humorous observations about daily events in the most informal and distinct approach to live comedy. Been a celebrity STANDUP COMEDAIN on CANVASS LAUGHTER CHAPTER,KENNY is sure to make you laugh until you cry! <br><br> <h3 class="para">DAY 2 : 5th February 2018</h3> </p>
<br>
<br>

<center>
<a class="sub" href="standup.php" target="_blank">Register here</a>
</center>

<H4 ALIGN="CENTER"> CONTACT:</H2>

<H4 ALIGN="CENTER">SOHAM: +917756378907</H2>
</body></html>