<html><head>
<style>

ul {
    list-style-type: none;
    margin: 10;
    padding: 0;
    overflow: hidden;
    background-color: black;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: grey;
}


</style>
</head><body>
<ul>
  <li><a class="active" href="http://localhost/first.php">Home</a></li>
  <li><a href="http://localhost/contact.php">Contact Us</a></li>
  <li><a href="http://localhost/about.php">About</a></li>
</ul>
<BR>
<H1 align="center">XIE DANCE +</H1>
<H2 ALIGN="CENTER">To Dance is an expression of one's individuality! 
So turn your dance modes On and come in groups to express yourself and show the world how well can you coordinate. 
</h2>
<br>
<a target="_blank" href="http://localhost/dnce+.php">To Register Click Here</a>
   
<h2 align="center">Spandan 2018 presents Clique Ecstasy, The Group Dance event of XIE!  </H2>
<H2 ALIGN="CENTER"> CONTACT:</H2>
<BR>
<H2 ALIGN="CENTER">CHAITRALI: +917756378907</H2>
</body></html>